### ISSUE TITLE
Suggestion: replace kirby with a more fluid animation

### ISSUE THREAD

**Issue by rotemdan** [nolanlawson/database-comparison#4]
Very useful work (thanks!), but I'm using this instead of the animated character (when resized of course), taken from [this blog](http://pttrnz.tumblr.com/), which also contains other alternatives (copyright unclear). It allows observing the pauses more precisely, including relatively short ones:

![perpetual](https://cloud.githubusercontent.com/assets/8589488/12535960/af843fd0-c29e-11e5-89b0-ee96d05583a4.gif)

An even more precise alternative would be to show a live plot based on "heartbeats" sent as timestamped messages using `postMessage`, or something like that, and measure the latency based on their arrival time, but that seems like a lot of work, so for now I find this relatively sufficient.

**Comment by nolanlawson** [comment]
Sorry, I just really like Kirby. :) Also this project basically served as a companion to a blog post, so I don't plan on updating it anymore. But please feel free to fork it and make your own test! A psychedelic version would be pretty sweet. ;)
